cleanrun: clean makerun

run:
	./project-1 "CNS 3060" is going to be fun

make run: make run

make: compile
	g++ project-1.o -o project-1

compile: project-1.cpp
	g++ -c project-1.cpp

clean:
	rm -rf *o project-1

